name: .NET

on:
  push:
    branches: [ main, mihir-gautam-patch-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --logger "trx;LogFileName=test_results.xml" --results-directory TestResults --configuration Release
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: EmployeeManagement
        path: bin/Release/netcoreapp3.1
